/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Horde;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

import java.io.File;
import java.net.URL;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);

    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        URL url = new File("src/main/resources/HordeUI.fxml").toURI().toURL();
        FXMLLoader loader = new FXMLLoader(url);
        Parent root = loader.load();
        Controller controller = loader.getController();
        controller.initStuff();
        primaryStage.setTitle("Horde");
        primaryStage.setScene(new Scene(root, Double.MAX_VALUE, Double.MAX_VALUE));
        primaryStage.getIcons().add(new Image("file:src/main/resources/HordeUI.jpg")); //add icon to stage
        TrayIconClass.setupTray(controller);
        primaryStage.show();
        controller.setStage(primaryStage);

    }

    @Override
    public void stop() throws Exception {
        super.stop();
        Database.close();
    }

}//end main class
